@library_automation_back_end_HostAddress = https://localhost:3001
@AccessTokenAdmin = AdminAccessTokenHere

GET {{library_automation_back_end_HostAddress}}/api/admin/GetAllDesires
Authorization: Bearer {{AccessTokenAdmin}}

###

GET {{library_automation_back_end_HostAddress}}/api/admin/GetBorrowedBooks
Authorization: Bearer {{AccessTokenAdmin}}

###

GET {{library_automation_back_end_HostAddress}}/api/admin/GetReservedBooks
Authorization: Bearer {{AccessTokenAdmin}}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AcceptBorrow
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "desireId" : "1"
}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AcceptReserveBorrow
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "desireId" : "1"
}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AcceptReturn
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "desireId" : "1"
}

###

DELETE {{library_automation_back_end_HostAddress}}/api/admin/RejectDesire
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "desireId" : "1"
}

###


POST {{library_automation_back_end_HostAddress}}/api/admin/AddBook
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "name" : "Test Book 1",
  "year" : 2022,
  "count" : 10,
  "pageCount" : 555,
  "language" : "English",
  "publisher" : "Panama",
  "authors" : ["Test Author 1", "Test Author 2"],
  "categories" : ["Test Category 1", "Test Category 2"]
}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AddPublisher
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
    "name": "Test Publisher 1",
    "country": "spain"
}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AddAuthor
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "authors" : [
    {  
      "name": "Test Author 1",
      "country": "Turkiye"
    },
    {  
      "name": "Test Author 2",
      "country": "Azerbaijan"
    }
  ]
}

###

POST {{library_automation_back_end_HostAddress}}/api/admin/AddCategory
Content-Type: application/json
Authorization: Bearer {{AccessTokenAdmin}}

{
  "categories" : [
    {  
      "name": "Test Category 1"
    },
    {  
      "name": "Test Category 2"
    }
  ]
}

###