@library_automation_back_end_HostAddress = https://localhost:3001

POST {{library_automation_back_end_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@hotmail.com",
  "password": "admin123"
}

###

POST {{library_automation_back_end_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@hotmail.com",
  "name": "TestName",
  "surname": "TestSurname",
  "countryId": 1,
  "password": "test123",
  "confirmPassword": "test123"
}

###

### POST {{library_automation_back_end_HostAddress}}/api/auth/refresh

###


