@library_automation_back_end_HostAddress = https://localhost:3001

GET {{library_automation_back_end_HostAddress}}/api/library/getbook?bookid=3

###

GET {{library_automation_back_end_HostAddress}}/api/library/searchbook?search=yapý&page=0&size=5

###